services:
    php_fast_cgi_speedfony.symfony_message_factory:
        class: Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory

    php_fast_cgi_speedfony.psr_message_factory:
        class: Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory

    php_fast_cgi_speedfony.daemon_factory:
        class: PHPFastCGI\FastCGIDaemon\DaemonFactory

    php_fast_cgi_speedfony.kernel_wrapper:
        class: PHPFastCGI\SpeedfonyBundle\Bridge\KernelWrapper
        arguments: ['@kernel', '@php_fast_cgi_speedfony.symfony_message_factory', '@php_fast_cgi_speedfony.psr_message_factory']

    php_fast_cgi_speedfony.daemon_run_command:
        class: PHPFastCGI\FastCGIDaemon\Command\DaemonRunCommand
        arguments: ['daemon:run', 'Expose this application to the FastCGI daemon', '@php_fast_cgi_speedfony.daemon_factory', '@php_fast_cgi_speedfony.kernel_wrapper']
        tags:
            - { name: console.command }
