services:
    andrew_carter_uk_speedfony.daemon_run_command:
        class: PHPFastCGI\SpeedfonyBundle\Command\DaemonRunCommand
        arguments: [@kernel]
        tags:
            - { name: console.command }
