services:
    php_fast_cgi_speedfony.kernel_wrapper:
        class: PHPFastCGI\SpeedfonyBundle\Bridge\KernelWrapper
        arguments: ['@kernel']

    php_fast_cgi_speedfony.daemon_run_command:
        class: PHPFastCGI\FastCGIDaemon\Command\DaemonRunCommand
        arguments: ['@php_fast_cgi_speedfony.kernel_wrapper', ~, 'speedfony:run']
        tags:
            - { name: console.command }
