services:
    php_fast_cgi_speedfony.daemon_run_command:
        class: PHPFastCGI\SpeedfonyBundle\Command\DaemonRunCommand
        arguments: [@kernel]
        tags:
            - { name: console.command }
